"""initial_schema

Revision ID: initial_schema
Revises:
Create Date: 2026-03-24

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('principals',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('principal_type', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('trust_tier', sa.String(length=50), nullable=False),
    sa.Column('disclosure_mode', sa.String(length=50), nullable=False),
    sa.Column('disclosure_template', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('locale', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_principal_email', 'principals', ['email'], unique=False)
    op.create_index('idx_principal_external_id', 'principals', ['external_id'], unique=False)
    op.create_index('idx_principal_type', 'principals', ['principal_type'], unique=False)

    op.create_table('relationships',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('from_principal_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('to_principal_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('relationship_class', sa.String(length=50), nullable=False),
    sa.Column('sensitivity', sa.String(length=50), nullable=False),
    sa.Column('default_delegation_profile', sa.JSON(), nullable=True),
    sa.Column('custom_delegation_profile', sa.JSON(), nullable=True),
    sa.Column('alias', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('first_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['from_principal_id'], ['principals.id'], ),
    sa.ForeignKeyConstraint(['to_principal_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_relationship_class', 'relationships', ['relationship_class'], unique=False)
    op.create_index('idx_relationship_pair', 'relationships', ['from_principal_id', 'to_principal_id'], unique=True)
    op.create_index('idx_relationship_sensitivity', 'relationships', ['sensitivity'], unique=False)

    op.create_table('threads',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('objective_title', sa.String(length=200), nullable=False),
    sa.Column('objective_description', sa.Text(), nullable=True),
    sa.Column('objective_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('delegation_profile_name', sa.String(length=100), nullable=True),
    sa.Column('delegation_level', sa.String(length=50), nullable=True),
    sa.Column('delegation_max_actions_per_hour', sa.Integer(), nullable=True),
    sa.Column('delegation_max_messages_per_thread', sa.Integer(), nullable=True),
    sa.Column('delegation_max_consecutive_touches', sa.Integer(), nullable=True),
    sa.Column('delegation_allowed_actions', sa.JSON(), nullable=True),
    sa.Column('delegation_escalation_rules', sa.JSON(), nullable=True),
    sa.Column('owner_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('responsible_principal_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('participant_ids', sa.JSON(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('current_step', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_escalation_reason', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_thread_owner_status', 'threads', ['owner_id', 'status'], unique=False)
    op.create_index('idx_thread_risk_level', 'threads', ['risk_level'], unique=False)
    op.create_index('idx_thread_status_updated', 'threads', ['status', 'updated_at'], unique=False)

    op.create_table('external_bindings',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('thread_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('channel_account_id', sa.String(length=255), nullable=True),
    sa.Column('external_thread_key', sa.String(length=500), nullable=True),
    sa.Column('external_message_key', sa.String(length=500), nullable=True),
    sa.Column('message_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('sync_state', sa.String(length=50), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('is_inbound', sa.Boolean(), nullable=False),
    sa.Column('is_outbound', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('sync_direction', sa.String(length=50), nullable=False),
    sa.Column('external_subject', sa.String(length=500), nullable=True),
    sa.Column('external_sender', sa.String(length=500), nullable=True),
    sa.Column('external_recipients', sa.JSON(), nullable=True),
    sa.Column('external_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_binding_channel_message', 'external_bindings', ['channel', 'external_message_key'], unique=False)
    op.create_index('idx_binding_channel_thread', 'external_bindings', ['channel', 'external_thread_key'], unique=False)
    op.create_index('idx_binding_sync_state', 'external_bindings', ['sync_state'], unique=False)
    op.create_index('idx_binding_thread', 'external_bindings', ['thread_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('thread_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('authored_mode', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('sender_principal_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('author_principal_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('approver_principal_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('parent_message_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('reply_to_external_id', sa.String(length=255), nullable=True),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('approval_request_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('disclosure', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_status', sa.String(length=50), nullable=True),
    sa.Column('delivery_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_authored_mode', 'messages', ['authored_mode'], unique=False)
    op.create_index('idx_message_external_id', 'messages', ['external_message_id'], unique=False)
    op.create_index('idx_message_thread', 'messages', ['thread_id'], unique=False)
    op.create_index('idx_message_thread_created', 'messages', ['thread_id', 'created_at'], unique=False)

    op.create_table('thread_events',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('thread_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('actor_principal_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=True),
    sa.Column('causal_event_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('causal_ref', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('thread_status_before', sa.String(length=50), nullable=True),
    sa.Column('thread_status_after', sa.String(length=50), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('is_replayed', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_event_idempotency', 'thread_events', ['idempotency_key'], unique=False)
    op.create_index('idx_event_occurred_at', 'thread_events', ['occurred_at'], unique=False)
    op.create_index('idx_event_thread_sequence', 'thread_events', ['thread_id', 'sequence_number'], unique=True)
    op.create_index('idx_event_thread_type', 'thread_events', ['thread_id', 'event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_event_thread_type', table_name='thread_events')
    op.drop_index('idx_event_thread_sequence', table_name='thread_events')
    op.drop_index('idx_event_occurred_at', table_name='thread_events')
    op.drop_index('idx_event_idempotency', table_name='thread_events')
    op.drop_table('thread_events')

    op.drop_index('idx_message_thread_created', table_name='messages')
    op.drop_index('idx_message_thread', table_name='messages')
    op.drop_index('idx_message_external_id', table_name='messages')
    op.drop_index('idx_message_authored_mode', table_name='messages')
    op.drop_table('messages')

    op.drop_index('idx_binding_thread', table_name='external_bindings')
    op.drop_index('idx_binding_sync_state', table_name='external_bindings')
    op.drop_index('idx_binding_channel_thread', table_name='external_bindings')
    op.drop_index('idx_binding_channel_message', table_name='external_bindings')
    op.drop_table('external_bindings')

    op.drop_index('idx_thread_status_updated', table_name='threads')
    op.drop_index('idx_thread_risk_level', table_name='threads')
    op.drop_index('idx_thread_owner_status', table_name='threads')
    op.drop_table('threads')

    op.drop_index('idx_relationship_sensitivity', table_name='relationships')
    op.drop_index('idx_relationship_pair', table_name='relationships')
    op.drop_index('idx_relationship_class', table_name='relationships')
    op.drop_table('relationships')

    op.drop_index('idx_principal_type', table_name='principals')
    op.drop_index('idx_principal_external_id', table_name='principals')
    op.drop_index('idx_principal_email', table_name='principals')
    op.drop_table('principals')
    # ### end Alembic commands ###
